name: CI Audit

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: node cli.js --url=https://example.com --save
      - uses: actions/upload-artifact@v4
        with:
          name: audit-results
          path: data/results.json
